name: Build gfw.dat

on:
  workflow_run:
    workflows: ["main"] 
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - 'gfwlist.txt'
  workflow_dispatch:

jobs:
  build:
    # 如果是 workflow_run 触发，要求上游 Workflow 必须成功才执行
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25'
          cache: false
          
      - name: Prepare Data Directory and Build gfw.dat
        run: |
          mkdir -p build_data
          cp gfwlist.txt build_data/gfw
          go install github.com/v2fly/domain-list-community@latest
          $(go env GOPATH)/bin/domain-list-community -datapath=build_data -outputname=gfw.dat -outputdir=./
          rm -rf build_data

      - name: Commit and Push gfw.dat to Repository
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "auto: update gfw.dat [skip ci]"
          file_pattern: "gfw.dat"
